# server {
#     listen 80 default_server;
#     server_name localhost 127.0.0.1 _;

#     access_log off;

#     location /health {
#         default_type application/json;
#         return 200 '{"status":"ok"}';
#     }

#     location / {
#         return 404;
#     }
# }
