resolver 127.0.0.11 valid=30s ipv6=off;
resolver_timeout 5s;

include /etc/nginx/conf.d/ssl.conf;

server {
    listen 80 default_server;
    server_name _;

    return 444;
}

server {
    listen 443 default_server;
    server_name _;

    ssl reject handshake on;
}

include /etc/nginx/projects/*.conf;